# Netlify Configuration for PDF Viewer App

[build]
  publish = "."
  command = "echo 'No build required'"

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/vi"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/en"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/vi-en"
  to = "/index.html"
  status = 200

# Catch-all redirect for any other path
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/pdfs/*"
  [headers.values]
    Content-Type = "application/pdf"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"